#pragma once

#define SUCCESS (0)
#define FAILURE_BADPARAM (-1)
#define FAILURE_BADALLOC (-2)
#define UNEXECUTED (-3)

#define AVX2_ALIGNMENT (32u)

#define AVX2_FLOAT_STRIDE (8u)
#define AVX2_FLOAT_BATCH_MASK (~7u)
#define AVX2_FLOAT_REMAIN_MASK (7u)

#define AVX2_DOUBLE_STRIDE (4u)
#define AVX2_DOUBLE_BATCH_MASK (~3u)
#define AVX2_DOUBLE_REMAIN_MASK (3u)

#define AVX2_EPI32_STRIDE (8u)
#define AVX2_EPI32_BATCH_MASK (~7u)
#define AVX2_EPI32_REMAIN_MASK (7u)

#define AVX2_EPI64_STRIDE (4u)
#define AVX2_EPI64_BATCH_MASK (~3u)
#define AVX2_EPI64_REMAIN_MASK (3u)

#define MAX_SORT_STRIDE (0x10000000u)